
// i dont think VerifyError is exported

// let VerifyError = require("../../../lib/errors").VerifyError;
// let expect = require('chai').expect;

// describe("VerifyError", () => {
//     it("Create error - valid data", () => {
//         let message = {
//             error: "Something went wrong",
//             error_description: "its a bad error"
//         }

//         let name = "Error";
//         let errorStatus = "100";

//         let error = new VerifyError(name, message, errorStatus);

//         console.log(error);


//     })
// })
